### ISSUE TITLE
Começar a implementação de JPA e RMI

### ISSUE THREAD

**Issue by Joao-Victor-Bonfim** [biel97/ImplicareTP04#1]
Quem vai ser o responsável pelo o quê?

**Comment by Joao-Victor-Bonfim** [comment]
Tutoriais e fontes de pesquisa:
https://vladmihalcea.com/
https://www.caelum.com.br/apostila-java-web/uma-introducao-pratica-ao-jpa-com-hibernate/

**Comment by biel97** [comment]
Vamos implementar JPA no Domain, mas deixando o Domain antigo. Lembrando que para as tabela que tem mais de uma chave temos que fazer uma classe Domain para chave das tabelas e outtro Domain para a tabela passando o Domain de chaves.

**Comment by biel97** [comment]
Pode começar a fazer, escolhe uma certa quantidade de Domain pra vc fazer.

**Comment by biel97** [comment]
antlr-2.7.7.jar
classmate-1.3.0.jar
dom4j-1.6.1.jar
hibernate-commons-annotations-5.0.1.Final.jar
hibernate-core-5.2.17.Final.jar
hibernate-jpa-2.1-api-1.0.0.Final.jar
jandex-2.0.3.Final.jar
javassist-3.22.0-GA.jar
jboss-logging-3.3.1.Final.jar
jboss-transaction-api_1.2_spec-1.0.1.Final.jar
